---
title:           summary AUC
author:          Dennis Wollersheim
date:            12.03.2020
linkcolor:       cyan
citecolor:       grey
output: 
    html_document:
      code_folding: hide
---

\tableofcontents

```{r load_data_outer, include=FALSE}

library(zoo)
library(tidyverse)
library(readxl)
library(janitor)
library(forecast)
library(seismicRoll)
library(pracma)
library(kableExtra)
library(knitr)

options(error=stop)
read_excel('data/MILO_read_out_Dennis.xlsx') %>%
  clean_names() %>%
  rename_all( str_replace, 'time_','') %>%
  pivot_longer(-file, 
               names_to=c('.value','sheet_n'),
               names_pattern='(.*)_(.)' )  %>%
  filter( start > 0) %>% 
  rename(excel_filename = file )%>%
  { . } -> df_sheets




base_dir = 'data/P/'
output_dir = 'docs/'
files=c()

for(i in 1:nrow(df_sheets)) {
  base_file = df_sheets[ i, ]$excel_filename
  #print(base_file )
  xls_input_file=paste0( base_dir, base_file, '.xlsx')
  sheet_n = df_sheets[i,]$sheet_n
  sheet = df_sheets[i,]$sheet
  output_file = paste0( base_file, '_', sheet_n, '.html')

  if (!file.exists(xls_input_file)) print(xls_input_file)

#  try({
    rv = rmarkdown::render( 
      input = 'analysis/process_one_sheet.Rmd', 
      output_format = "html_document",
      output_dir=output_dir,
      output_file = output_file, 
      knit_root_dir=pwd(),
      envir=new.env(),
      params=list(
        xls_input_file = xls_input_file,
        base_file = base_file,
        sheet_n = sheet_n %>% as.numeric(),
        sheet = df_sheets[i,]$sheet,
        start_timestamp = df_sheets[i,]$start
      )
    )
#  })
  #knitr::knit( text = src)
  files = c(files, paste0( '<a href="',
                          output_file,
                          '">FIlE = ',
                          base_file,
                          '. SHEET = ',
                          sheet,
                          '</a><p/>'
  ))
}

```

```{r output_outer, echo=FALSE, results='asis'}
csv_file_out = 'results_summary.csv'
map(files, cat ) ->a

cat(paste0( '<p/><p/><p/><p/><a href=', csv_file_out,'>results_summary.csv</a>'))

col_types = cols(
                 base_file = col_character(),
                 sheet_n = col_double(),
                 max_t = col_double(),
                 min_t = col_double(),
                 end_t = col_double(),
                 full_auc = col_double(),
                 upper_auc = col_double(),
                 raw = col_double(),
                 smoothed = col_double(),
                 loess = col_double(),
                 cleaned = col_double()
)
#

list.files(path='data/output/', pattern='.*csv', full.names=TRUE) %>%
  map( read_csv, col_types=col_types ) %>% 
  bind_rows() %>%
  { . } -> df_csv

df_csv %>% write_csv(paste0('docs/',csv_file_out))

```

```{r write_csv, echo=FALSE}

df_csv %>% 
  kableExtra::kable()

```



